# Generated by Django 4.2.7 on 2023-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(default='Kowbasuha', max_length=255, null=True),
        ),
    ]
